name: AutoLab
description: A new Flutter application.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter_markdown: ^0.6.2
  mailto: ^2.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.18
  model: ^0.1.3
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  dcdg: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.5
  json_serializable: ^6.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - Assets/Images/
    - Assets/
  fonts:
    - family: Roboto
      fonts:
        - asset: Assets/Roboto-Light.ttf
          weight: 600
